# Generated by Django 4.2.1 on 2023-08-03 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mycloud', '0002_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authtype', models.BooleanField(default=False)),
                ('doc', models.CharField(max_length=45)),
                ('userA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userA_auth_set', to=settings.AUTH_USER_MODEL)),
                ('userB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userB_auth_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
