# Generated by Django 4.2.1 on 2023-08-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycloud', '0003_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='file',
            field=models.FileField(default='default', upload_to='files/'),
        ),
    ]
